#pragma once

#define TOMATO_MOUSE_BUTTON_1         0
#define TOMATO_MOUSE_BUTTON_2         1
#define TOMATO_MOUSE_BUTTON_3         2
#define TOMATO_MOUSE_BUTTON_4         3
#define TOMATO_MOUSE_BUTTON_5         4
#define TOMATO_MOUSE_BUTTON_6         5
#define TOMATO_MOUSE_BUTTON_7         6
#define TOMATO_MOUSE_BUTTON_8         7
#define TOMATO_MOUSE_BUTTON_LAST      TOMATO_MOUSE_BUTTON_8
#define TOMATO_MOUSE_BUTTON_LEFT      TOMATO_MOUSE_BUTTON_1
#define TOMATO_MOUSE_BUTTON_RIGHT     TOMATO_MOUSE_BUTTON_2
#define TOMATO_MOUSE_BUTTON_MIDDLE    TOMATO_MOUSE_BUTTON_3
