#pragma once

#ifndef MAX_VERTEX_NUMBER
	#define MAX_VERTEX_NUMBER 1024
#endif // !MAX_VERTEX_NUMBER

#ifndef MAX_INDEX_NUMBER
	#define MAX_INDEX_NUMBER 8 * MAX_VERTEX_NUMBER
#endif // !MAX_VERTEX_NUMBER

#ifndef MAX_TEXTURE_SLOTS
	#define MAX_TEXTURE_SLOTS 32
#endif // MAX_TEXTURE_SLOTS


